apiVersion: v1
kind: Service
metadata:
  name: {{ include "snitch.fullname" . }}-console
  labels:
    {{- include "snitch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "snitch.name" . }}-console
    app.kubernetes.io/instance: {{ .Release.Name }}
