apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamdal.fullname" . }}-console
  labels:
    {{- include "streamdal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "streamdal.name" . }}-console
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "streamdal.name" . }}-console
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: streamdal-console
          image: "streamdal/console:v0.1.31" # Fixed the image and tag definition
          ports:
            - containerPort: 8080
          env:
            - name: STREAMDAL_CONSOLE_GRPC_WEB_URL
              value: "http://streamdal-server.{{ .Release.Namespace }}.svc.cluster.local:8083"
            - name: STREAMDAL_CONSOLE_GRPC_AUTH_TOKEN
              value: {{ .Values.env.STREAMDAL_SERVER_AUTH_TOKEN | quote }}
            - name: STREAMDAL_DEMO
              value: {{ .Values.env.STREAMDAL_DEMO | quote }}
          volumeMounts:
          - mountPath: /root/.cache
            name: esbuild-cache
      volumes:
      - name: esbuild-cache
        emptyDir: {}
