version: "3.8"

services:
  streamdal-aes-gen:
    image: busybox
    volumes:
      - ${PWD}/assets/env:/assets/env
    command: sh -c "/assets/env/script.sh"
    restart: "no"

  redis:
    container_name: streamdal-redis
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - streamdal-network

  streamdal-server:
    container_name: streamdal-server
    image: streamdal/server:e074107
    depends_on:
      - streamdal-aes-gen
      - redis
    environment:
      - STREAMDAL_SERVER_NODE_NAME=node1
      - STREAMDAL_SERVER_AUTH_TOKEN=1234
      - STREAMDAL_SERVER_REDIS_URL=redis:6379
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - streamdal-network
    restart: on-failure

  envoy:
    build:
      context: assets/envoy
      dockerfile: Dockerfile
    container_name: streamdal-envoy
    depends_on:
      - streamdal-server
    ports:
      - "8083:8083"
    networks:
      - streamdal-network
    restart: on-failure

  streamdal-console:
    image: streamdal/console:v0.1.26
    container_name: streamdal-console
    depends_on:
      - envoy
    environment:
      - STREAMDAL_CONSOLE_GRPC_WEB_URL=http://envoy:8083
      - STREAMDAL_CONSOLE_GRPC_AUTH_TOKEN=1234
    ports:
      - "8080:8080"
    networks:
      - streamdal-network
volumes:
  redis-data:

networks:
  streamdal-network:
