apiVersion: v1
kind: Service
metadata:
  name: streamdal-console
  {{- if .Values.consoleService.loadBalancer.enabled }}
  annotations:
    {{- range $key, $value := .Values.consoleService.loadBalancer.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ if .Values.consoleService.loadBalancer.enabled }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
  {{- if .Values.consoleService.loadBalancer.enabled }}
  - name: {{ .Values.consoleService.loadBalancer.name }}
    port: {{ .Values.consoleService.loadBalancer.port }}
    targetPort: {{ .Values.consoleService.loadBalancer.targetPort }}
  {{- else }}
  - name: http
    port: 3000
    targetPort: 3000
  {{- end }}